# Generated by Django 4.0 on 2021-12-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firts_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
    ]
