# Generated by Django 4.0 on 2021-12-27 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheta', models.IntegerField(unique=True, validators=[django.core.validators.MaxLengthValidator(8), django.core.validators.MinLengthValidator(8)])),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='history',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='action',
            name='account',
        ),
        migrations.RemoveField(
            model_name='action',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='from_account',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='to_account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
