# Generated by Django 4.0 on 2021-12-27 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_delete_customuser'),
        ('bank', '0003_schet_remove_customer_user_remove_history_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='user.user'),
        ),
        migrations.AddField(
            model_name='action',
            name='schet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='action_schet', to='bank.schet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='from_schet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_schet', to='bank.schet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_schet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to_schet', to='bank.schet'),
            preserve_default=False,
        ),
    ]
