# Generated by Django 4.0 on 2021-12-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_schet_user_action_schet_transfer_from_schet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schet',
            name='scheta',
            field=models.IntegerField(unique=True),
        ),
    ]
