# Generated by Django 4.0 on 2022-01-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_schet_scheta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schet',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
