# Generated by Django 4.0 on 2022-01-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_alter_action_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schet',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
