# Generated by Django 4.0 on 2022-01-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_alter_schet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='schet',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
