# Generated by Django 4.0 on 2022-01-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_alter_action_amount_alter_schet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
