# Generated by Django 4.0 on 2022-01-08 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_alter_action_amount_alter_schet_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('title', models.CharField(max_length=255)),
                ('schet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_schet', to='bank.schet')),
            ],
        ),
    ]
