# Generated by Django 4.0 on 2022-01-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schet',
            name='scheta',
            field=models.IntegerField(max_length=8, unique=True),
        ),
    ]
