# Generated by Django 4.0 on 2022-01-11 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_alter_schet_scheta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schet',
            name='scheta',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(limit_value=8, message='Your schet must consist 8 numbers '), django.core.validators.MinValueValidator(limit_value=8, message='Your schet must consist 8 numbers ')]),
        ),
    ]
